#ifndef YYSTYPE
#define YYSTYPE int
#endif
#define	HTML_COMMENT	258
#define	HTML_CONDITIONAL_COMMENT	259
#define	DOUBLE_QUOTE_STRING	260
#define	SINGLE_QUOTE_STRING	261
#define	HEXCHARS	262
#define	TEXT	263
#define	TAG_NAME	264
#define	OPENING_TAG_BRACKET	265
#define	CLOSING_TAG_BRACKET	266
#define	SLASH	267
#define	ASSIGNMENT	268


extern YYSTYPE yylval;
