#line 1 "lexer.cpp"

#line 3 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 59
#define YY_END_OF_BUFFER 60
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[427] =
    {   0,
       58,   58,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   60,   58,   25,   26,
       25,   58,   58,   58,   55,   52,   54,   53,    3,    2,
        3,    7,    6,    7,    5,   11,   10,   11,    9,   15,
       14,   15,   13,   18,   17,   18,   21,   20,   21,   24,
       23,   24,   58,   25,   25,   58,   58,   58,    0,   57,
       58,   58,   58,   58,    0,   56,   58,    0,    0,    0,
        0,    4,    8,   12,    0,    0,    0,   58,   58,   57,
        0,    0,   58,    0,   58,   56,    0,   58,    0,    0,
        0,    0,    0,    1,    0,    0,    0,   58,   58,    0,

       58,   51,    0,    0,   49,    0,    0,    0,   58,   58,
        0,   58,   50,    0,    0,    0,    0,    0,   58,   58,
        0,   58,    0,   48,    0,    0,   22,   58,   58,    0,
        0,   47,    0,    0,   58,   58,    0,    0,    0,   19,
        0,    0,    0,    0,   16,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   29,    0,   32,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   28,   27,   31,   30,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       33,    0,    0,    0,   45,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   39,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   37,    0,   43,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   36,    0,    0,    0,    0,    0,    0,   34,
        0,    0,   35,   41,    0,    0,    0,   38,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   46,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   40,    0,    0,    0,   44,
        0,    0,    0,    0,   42,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   12,    1,
       13,   14,    1,    1,    1,    1,    1,   15,    1,   16,
       17,   18,    1,    1,    1,   19,   20,   21,   22,   23,
        1,   24,   25,    1,    1,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,    1,   35,   36,   37,    1,
       38,   39,    1,    1,    1,    1,   40,    1,   41,   42,

       43,   44,   45,   46,   47,    1,    1,   48,   49,   50,
       51,   52,    1,   53,   54,   55,    1,    1,   56,   57,
       58,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[444] =
    {   0,
        0,   17,    5,    6,   22,   26,   27,   28,   38,   39,
       12,   23,   44,   47,   48,   49,  977,    0,   51, 1032,
       57,   33,   73,   89, 1032,   57, 1032, 1032, 1032, 1032,
      968, 1032, 1032,  956, 1032, 1032, 1032,  955, 1032, 1032,
     1032,  953, 1032, 1032, 1032,  959, 1032, 1032,  958, 1032,
     1032,  956,    0,   64,   65,  936,  912,  114,   64,    0,
      119,   68,  156,  138,    4,    0,   84,  954,   32,  907,
      937, 1032, 1032, 1032,  900,  899,  895,  931,  886, 1032,
        0,  128,  165,   65,  209, 1032,    0,  181,   88,  908,
      858,  847,  855, 1032,  860,  802,  797,  811,  780,   74,

      262,  795,  776,  764, 1032,  757,  715,  723,  718,  668,
      137,  312, 1032,  666,  673,  667,  641,  669,  656,  614,
      141,  190,  589, 1032,  525,  531, 1032,  547,  523,  195,
      204, 1032,  509,  536,  544,  515,  211,  183,  496, 1032,
      133,  140,   76,  184, 1032,  469,  442,  435,  399,  197,
      196,  395,  360,  375,  349,  203,  222,  360,  329,  293,
      264,  212,  231,  291,  281,  250,  243,  235,  243,  216,
      215,  208,  203,  251,  238,  249,  198,  158,  153,  144,
      254,  261,  247,  151,  146,  133,  132,  257,  270,  110,
      120,  118,  114,  113,  269,  263,  286,  108,  101,   96,

       85,  285,  299,  300,   88,   78,   54,   38,  298,  305,
      307, 1032, 1032, 1032, 1032,  315,  314,  326,  329,  336,
      339,  346,  330,  349,  327,  337,  352,  357,  361,  355,
      358,  366,  368,  373,  375,  376,  377,  381,  386,  387,
      393,  400,  395,  405,  402,  407,  421,  411,  412,  418,
      423,  430,  431,  432,  437,  442,  450,  446,  447,  452,
     1032,  457,  460,  459, 1032,  468,  471,  466,  469,  476,
      478,  482,  487,  512,  489,  497,  503,  517,  498,  486,
      506,  505,  528,  537,  532,  534,  544,  549,  555,  552,
      556,  557,  564,  559,  562,  569,  572,  578,  573,  579,

      580,  583,  584,  598,  603,  600,  615,  587,  608,  610,
      621,  626,  623,  630,  634,  632,  635,  629,  637,  639,
      646,  640,  642,  653,  655,  664,  669, 1032,  674,  676,
      678,  682,  684,  690,  692,  694,  695,  696,  699,  701,
      703,  704,  705, 1032,  718, 1032,  726,  740,  719,  721,
      731,  733,  742,  744,  735,  746,  747,  756,  757,  762,
      763,  761, 1032,  769,  772,  776,  781,  786,  787, 1032,
      791,  797, 1032, 1032,  788,  799,  801, 1032,  792,  808,
      811,  812,  816,  813,  822,  826,  828,  831,  833,  835,
      836,  843,  842,  852,  853,  854,  863,  865,  874,  867,

      879, 1032,  880,  881,  882,  889,  883,  891,  894,  902,
      893,  906,  908,  909,  918, 1032,  919,  920,  931, 1032,
      933,  925,  940,  944, 1032, 1032,  983,  986,  989,  992,
      995,  998, 1001, 1004,    0, 1007, 1010, 1013, 1016, 1019,
     1022, 1025, 1028
    } ;

static const flex_int16_t yy_def[444] =
    {   0,
      427,  427,  428,  428,  429,  429,  430,  430,  431,  431,
      432,  432,  433,  433,  434,  434,  426,  435,  435,  426,
      426,  435,  436,  437,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  435,  435,  426,  435,  435,  436,  438,  435,
      436,  439,  436,  437,  440,  435,  441,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  435,  435,  426,
      442,  438,  436,  438,  436,  426,  443,  437,  440,  426,
      426,  426,  426,  426,  426,  426,  426,  435,  435,  438,

      436,  426,  426,  426,  426,  426,  426,  426,  435,  435,
      438,  436,  426,  426,  426,  426,  426,  426,  435,  435,
      438,  436,  426,  426,  426,  426,  426,  435,  435,  438,
      438,  426,  426,  426,  435,  435,  438,  438,  426,  426,
      426,  426,  438,  438,  426,  426,  426,  426,  426,  438,
      438,  426,  426,  426,  426,  438,  438,  426,  426,  426,
      426,  438,  438,  426,  426,  426,  426,  438,  438,  426,
      426,  426,  426,  438,  438,  438,  426,  426,  426,  426,
      438,  438,  438,  426,  426,  426,  426,  438,  438,  438,
      426,  426,  426,  426,  438,  438,  438,  426,  426,  426,

      426,  438,  438,  438,  426,  426,  426,  426,  438,  438,
      438,  426,  426,  426,  426,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      426,  438,  438,  438,  426,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  426,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  426,  438,  426,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  426,  438,  438,  438,  438,  438,  438,  426,
      438,  438,  426,  426,  438,  438,  438,  426,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  426,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  426,  438,  438,  438,  426,
      438,  438,  438,  438,  426,    0,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426
    } ;

static const flex_int16_t yy_nxt[1091] =
    {   0,
       53,   19,   20,   21,   22,   23,   24,   30,   30,   25,
       86,  426,   31,   31,   45,   26,   27,   28,   19,   20,
       21,   22,   23,   24,   33,   45,   25,   46,   33,   37,
       37,   34,   26,   27,   28,   34,   38,   38,   46,   35,
       41,   41,   87,   35,   39,   39,   48,   42,   42,   48,
       51,   51,   54,   56,   55,   43,   43,  215,   55,   49,
       55,   68,   49,   52,   52,   54,   55,   55,   55,   80,
       80,   84,   91,  214,   57,   59,   59,   84,   60,   80,
       61,   80,   59,   84,   84,   84,   92,   89,   59,   59,
       59,   65,   65,   89,   86,   66,  150,  213,   65,   89,

       89,   89,   81,   81,   65,   65,   65,  212,  111,  208,
       69,   62,   81,   70,   81,   80,   59,   59,   63,   60,
      207,   59,   59,   59,   60,  206,   87,   67,   82,   59,
       59,   59,  205,   80,   59,   59,   59,  100,  201,  200,
       65,   65,   80,  199,   66,  198,   80,   65,   81,  121,
      194,  193,   62,   65,   65,   65,  146,   62,   59,   59,
      130,   60,  197,  148,  192,   59,   81,   59,   59,  191,
       60,   59,   59,   59,   59,   81,   67,  187,  147,   81,
       59,   59,   59,   65,   65,  149,  186,   66,   80,   80,
       65,  185,   59,   59,   62,   60,   65,   65,   65,  131,

       80,   80,   80,   62,  137,   59,   59,   59,   80,   80,
       85,   59,   59,  138,   60,  168,   80,   80,   59,   67,
      143,   81,   81,  162,   59,   59,   59,   80,   62,  156,
      163,  184,  180,   81,   81,   81,   80,  179,  144,  151,
       80,   81,   81,   80,  178,  177,  173,   62,   80,   81,
       81,  157,   80,  172,   80,  176,   80,  183,  174,   80,
       81,  182,   80,  101,   59,   59,   80,   60,   80,   81,
      175,   59,  202,   81,   80,   80,   81,   59,   59,   59,
      188,   81,  195,  181,  171,   81,  169,   81,  203,   81,
       80,   80,   81,  189,  170,   81,  196,  190,  209,   81,

       62,   81,  210,   80,   80,   80,  216,   81,   81,  211,
       80,  167,   80,  112,   59,   59,  217,   60,  166,   80,
       80,   59,  220,   81,   81,  219,  122,   59,   59,   59,
      204,   80,   80,  228,   80,   80,   81,   81,   81,  218,
      222,   80,   80,   81,   80,   81,  223,  224,  225,  226,
       62,   80,   81,   81,   80,  227,  221,   80,  229,  232,
       80,  234,   80,   80,   81,   81,   80,   81,   81,  233,
      238,   80,  230,   80,   81,   81,  165,   81,   80,  235,
       80,   80,   80,  231,   81,  164,   80,   81,  236,  237,
       81,   80,   80,   81,  243,   81,   81,  161,   80,   81,

       80,  160,  247,  240,   81,   80,   81,   80,  159,  239,
       80,   81,   80,   81,   81,   81,   80,   80,  241,   81,
      242,  158,  252,   80,   81,   81,   80,  244,   80,  246,
      245,   81,  250,   81,  248,  261,   80,   80,   81,  251,
       81,  249,   80,   81,  253,   81,  255,  265,  256,   81,
       81,   80,   80,  155,  254,   80,   81,   80,  257,   81,
      258,   81,   80,  266,   80,   80,  259,  154,   81,   81,
       81,   80,  260,   80,   80,   81,   80,  273,  263,  262,
       81,   80,  274,   80,   81,   81,  264,   80,   81,  268,
       81,   80,   80,  267,   80,   81,  153,   81,   81,  270,

      271,  152,   80,   80,   81,  269,   81,   81,   80,   81,
       80,   80,  272,  145,   81,  276,   81,   80,  142,  275,
       81,  283,   80,  284,   81,   81,  288,   81,  279,  277,
      280,  285,  278,   80,  281,   81,   81,   80,  290,   80,
      282,   81,   80,   81,   81,  287,  294,  141,  293,   80,
       81,  286,  289,  140,   80,   81,  291,   80,  298,  292,
       80,   80,   80,  139,   80,  136,   81,   80,  135,   80,
       81,  305,   81,  134,   80,   81,  133,   80,   80,  304,
      296,  307,   81,   80,   80,   80,  295,   81,   80,   80,
       81,  300,   80,   81,   81,   81,  303,   81,  297,  308,

       81,  299,   81,   80,  313,   80,  301,   81,   80,  302,
       81,   81,  315,   80,  318,   80,   81,   81,   81,  306,
       80,   81,   81,  309,  317,   81,   80,  310,   80,  312,
      314,   80,  323,  311,  328,   80,   81,   80,   81,   80,
       80,   81,   80,  132,   80,   80,   81,   80,   81,  316,
      324,   80,  320,   81,  331,  325,  327,  319,   80,   81,
       80,   81,  334,  321,   81,  129,  322,   81,   81,   80,
       81,  326,   81,   81,   80,   81,  329,   81,   81,   80,
       81,   80,  335,   80,   81,  128,  127,   80,  126,   80,
      341,   81,  330,   81,  332,   80,  337,  344,  333,   80,

      346,   80,   81,  345,   80,  347,   80,   81,   80,   80,
       80,  336,   81,  125,   81,  124,   81,  123,  339,  340,
       81,  338,   81,   80,   80,  120,   80,  353,   81,  342,
       81,   80,   81,   81,   81,  354,   80,   81,   80,   81,
       80,   81,   81,   81,  350,   80,  343,   80,  355,   80,
      352,  363,   80,  348,  119,  349,   81,   81,  351,   81,
      356,   80,   80,  360,   81,  361,   80,   80,   80,   81,
      118,   81,  117,   81,  370,  357,  362,   80,   81,  358,
       81,   80,   81,  371,   81,   81,  373,  359,  364,  367,
      368,  374,   80,  378,   81,   81,   80,   80,  376,   81,

       81,   81,   80,  365,   80,  366,   80,   81,  377,  116,
       81,  115,  382,   80,   81,  369,   80,   80,   80,   81,
      386,   80,  114,  372,   81,   81,   81,   80,  375,   81,
       81,   80,  113,   80,  110,   81,   80,   81,   80,   81,
       80,   80,  379,  109,  383,  108,   81,   80,   80,   81,
       81,   81,  380,  381,   81,  387,  107,   80,   80,   80,
       81,  389,  384,  385,   81,  388,   81,  390,   80,   81,
      402,   81,   80,   81,   81,  404,  391,  392,  395,   80,
       81,   81,  393,  396,   80,   80,   80,   80,   80,  394,
       81,   81,   81,  398,   80,  397,   80,  409,   80,   80,

      106,   81,  105,   81,  104,   81,  399,   80,  400,  401,
      103,   80,   81,  416,   80,  102,  403,   81,   81,   81,
       81,   81,  407,   80,   80,  420,   99,   81,  408,   81,
       80,   81,   81,  405,  406,  412,   80,  410,   80,  421,
       81,  411,  414,  413,   81,   80,   81,   81,  417,  425,
       98,   97,   96,   95,   94,   93,   81,   81,   81,  418,
      415,   90,   79,   81,   78,   77,  419,   76,   75,   81,
       74,   81,   73,   72,  422,   71,  426,  426,   81,  423,
      426,  424,   81,   18,   18,   18,   29,   29,   29,   32,
       32,   32,   36,   36,   36,   40,   40,   40,   44,   44,

       44,   47,   47,   47,   50,   50,   50,   58,   58,   58,
       64,   64,   64,   59,   59,   59,   83,  426,   83,   65,
       65,   65,   88,  426,   88,   84,  426,   84,   89,  426,
       89,   17,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

static const flex_int16_t yy_chk[1091] =
    {   0,
      435,    1,    1,    1,    1,    1,    1,    3,    4,    1,
       65,    0,    3,    4,   11,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    5,   12,    2,   11,    6,    7,
        8,    5,    2,    2,    2,    6,    7,    8,   12,    5,
        9,   10,   65,    6,    7,    8,   13,    9,   10,   14,
       15,   16,   19,   22,   19,    9,   10,  208,   21,   13,
       21,   26,   14,   15,   16,   54,   55,   54,   55,   59,
       84,   62,   69,  207,   22,   23,   23,   62,   23,  100,
       23,  143,   23,   62,   62,   62,   69,   67,   23,   23,
       23,   24,   24,   67,   89,   24,  143,  206,   24,   67,

       67,   67,   59,   84,   24,   24,   24,  205,  100,  201,
       26,   23,  100,   26,  143,  190,   58,   58,   23,   58,
      200,   61,   61,   58,   61,  199,   89,   24,   61,   58,
       58,   58,  198,   82,   61,   61,   61,   82,  194,  193,
       64,   64,  111,  192,   64,  191,  121,   64,  190,  111,
      187,  186,   58,   64,   64,   64,  141,   61,   63,   63,
      121,   63,  190,  142,  185,   63,   82,   83,   83,  184,
       83,   63,   63,   63,   83,  111,   64,  180,  141,  121,
       83,   83,   83,   88,   88,  142,  179,   88,  138,  144,
       88,  178,  122,  122,   63,  122,   88,   88,   88,  122,

      130,  151,  150,   83,  130,  122,  122,  122,  156,  131,
       63,   85,   85,  131,   85,  162,  137,  162,   85,   88,
      137,  138,  144,  156,   85,   85,   85,  157,  122,  150,
      157,  177,  173,  130,  151,  150,  163,  172,  138,  144,
      168,  156,  131,  175,  171,  170,  167,   85,  169,  137,
      162,  151,  183,  166,  176,  169,  174,  176,  168,  181,
      157,  175,  188,   85,  101,  101,  182,  101,  196,  163,
      168,  101,  195,  168,  195,  189,  175,  101,  101,  101,
      181,  169,  188,  174,  165,  183,  163,  176,  196,  174,
      202,  197,  181,  182,  164,  188,  189,  183,  202,  182,

      101,  196,  203,  209,  203,  204,  209,  195,  189,  204,
      210,  161,  211,  101,  112,  112,  210,  112,  160,  217,
      216,  112,  217,  202,  197,  216,  112,  112,  112,  112,
      197,  218,  225,  223,  219,  223,  209,  203,  204,  211,
      219,  220,  226,  210,  221,  211,  220,  220,  221,  222,
      112,  222,  217,  216,  224,  222,  218,  227,  224,  226,
      230,  227,  228,  231,  218,  225,  229,  219,  223,  226,
      229,  232,  225,  233,  220,  226,  159,  221,  234,  228,
      235,  236,  237,  225,  222,  158,  238,  224,  228,  228,
      227,  239,  240,  230,  234,  228,  231,  155,  241,  229,

      243,  154,  238,  231,  232,  242,  233,  245,  153,  230,
      244,  234,  246,  235,  236,  237,  248,  249,  232,  238,
      233,  152,  243,  250,  239,  240,  247,  235,  251,  237,
      236,  241,  241,  243,  239,  252,  253,  254,  242,  242,
      245,  240,  255,  244,  244,  246,  246,  256,  247,  248,
      249,  258,  259,  149,  245,  257,  250,  260,  248,  247,
      249,  251,  262,  257,  264,  263,  250,  148,  252,  253,
      254,  268,  251,  266,  269,  255,  267,  266,  254,  253,
      256,  270,  267,  271,  258,  259,  255,  272,  257,  259,
      260,  280,  273,  258,  275,  262,  147,  264,  263,  262,

      263,  146,  276,  279,  268,  260,  266,  269,  277,  267,
      282,  281,  264,  139,  270,  269,  271,  274,  136,  268,
      272,  274,  278,  274,  280,  273,  278,  275,  272,  270,
      273,  275,  271,  283,  273,  276,  279,  285,  280,  286,
      273,  277,  284,  282,  281,  277,  284,  135,  283,  287,
      274,  276,  279,  134,  288,  278,  281,  290,  288,  282,
      289,  291,  292,  133,  294,  129,  283,  295,  128,  293,
      285,  295,  286,  126,  296,  284,  125,  297,  299,  294,
      286,  297,  287,  298,  300,  301,  285,  288,  302,  303,
      290,  290,  308,  289,  291,  292,  293,  294,  287,  298,

      295,  289,  293,  304,  303,  306,  291,  296,  305,  292,
      297,  299,  305,  309,  308,  310,  298,  300,  301,  296,
      307,  302,  303,  299,  307,  308,  311,  300,  313,  302,
      304,  312,  313,  301,  318,  314,  304,  316,  306,  315,
      317,  305,  319,  123,  320,  322,  309,  323,  310,  306,
      314,  321,  310,  307,  321,  315,  317,  309,  324,  311,
      325,  313,  324,  311,  312,  120,  312,  318,  314,  326,
      316,  316,  315,  317,  327,  319,  319,  320,  322,  329,
      323,  330,  325,  331,  321,  119,  118,  332,  117,  333,
      332,  324,  320,  325,  322,  334,  327,  335,  323,  336,

      337,  338,  326,  336,  339,  338,  340,  327,  341,  342,
      343,  326,  329,  116,  330,  115,  331,  114,  330,  331,
      332,  329,  333,  345,  349,  110,  350,  345,  334,  333,
      335,  347,  336,  337,  338,  347,  351,  339,  352,  340,
      355,  341,  342,  343,  341,  348,  334,  353,  348,  354,
      343,  356,  357,  339,  109,  340,  345,  349,  342,  350,
      349,  358,  359,  353,  347,  354,  362,  360,  361,  351,
      108,  352,  107,  355,  364,  350,  355,  365,  348,  351,
      353,  366,  354,  365,  356,  357,  367,  352,  357,  360,
      361,  368,  369,  375,  358,  359,  371,  379,  371,  362,

      360,  361,  372,  358,  376,  359,  377,  364,  372,  106,
      365,  104,  377,  380,  366,  362,  381,  382,  384,  367,
      382,  383,  103,  366,  368,  369,  375,  385,  369,  371,
      379,  386,  102,  387,   99,  372,  388,  376,  389,  377,
      390,  391,  376,   98,  379,   97,  380,  393,  392,  381,
      382,  384,  376,  376,  383,  383,   96,  394,  395,  396,
      385,  385,  380,  381,  386,  384,  387,  386,  397,  388,
      398,  389,  400,  390,  391,  400,  387,  388,  391,  399,
      393,  392,  389,  392,  401,  403,  404,  405,  407,  390,
      394,  395,  396,  394,  406,  393,  408,  406,  411,  409,

       95,  397,   93,  398,   92,  400,  395,  410,  396,  397,
       91,  412,  399,  413,  414,   90,  399,  401,  403,  404,
      405,  407,  404,  415,  417,  418,   79,  406,  405,  408,
      422,  411,  409,  401,  403,  409,  419,  407,  421,  419,
      410,  408,  411,  410,  412,  423,  413,  414,  414,  424,
       78,   77,   76,   75,   71,   70,  415,  417,  418,  415,
      412,   68,   57,  422,   56,   52,  417,   49,   46,  419,
       42,  421,   38,   34,  421,   31,   17,    0,  423,  422,
        0,  423,  424,  427,  427,  427,  428,  428,  428,  429,
      429,  429,  430,  430,  430,  431,  431,  431,  432,  432,

      432,  433,  433,  433,  434,  434,  434,  436,  436,  436,
      437,  437,  437,  438,  438,  438,  439,    0,  439,  440,
      440,  440,  441,    0,  441,  442,    0,  442,  443,    0,
      443,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      426,  426,  426,  426,  426,  426,  426,  426,  426,  426
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[60] =
    {   0,
0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 
    1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define YY_NO_UNISTD_H 1
#line 6 "lexer.l"
    #include <stdio.h>
    #include <io.h>
    #include <string>
    #include "utils.h"
    #include "debug.h"
    #include "grammar.cpp.h"
    #pragma warning( disable:4996 )
    #pragma warning( disable:5033 )

    extern int yyerror(const char * err);
    int g_LexerColumn = 0;
#line 867 "lexer.cpp"

#line 869 "lexer.cpp"

#define INITIAL 0
#define comment 1
#define script 2
#define style 3
#define xml 4
#define script_paired 5
#define style_paired 6
#define xml_paired 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "lexer.l"

#line 1095 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 427 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1032 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "lexer.l"
{ DEBUG_MESSAGE("COMMENT ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);  BEGIN(INITIAL);                  }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 31 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                }
	YY_BREAK
case YY_STATE_EOF(comment):
#line 32 "lexer.l"
{ ERROR_MESSAGE("Unclosed comment", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                              }
	YY_BREAK



case 4:
YY_RULE_SETUP
#line 38 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT SINGLE ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);  BEGIN(INITIAL);                 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED START", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(script_paired);            }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 40 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                     }
	YY_BREAK
case YY_STATE_EOF(script):
#line 41 "lexer.l"
{ ERROR_MESSAGE("Unclosed <script> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                   }
	YY_BREAK



case 8:
YY_RULE_SETUP
#line 47 "lexer.l"
{ DEBUG_MESSAGE("STYLE SINGLE ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED START", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(style_paired);            }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 49 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                    }
	YY_BREAK
case YY_STATE_EOF(style):
#line 50 "lexer.l"
{ ERROR_MESSAGE("Unclosed <style> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                  }
	YY_BREAK



case 12:
YY_RULE_SETUP
#line 56 "lexer.l"
{ DEBUG_MESSAGE("XML SINGLE ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 57 "lexer.l"
{ DEBUG_MESSAGE("XML PAIRED START", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(xml_paired);                }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 58 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                   }
	YY_BREAK
case YY_STATE_EOF(xml):
#line 59 "lexer.l"
{ ERROR_MESSAGE("Unclosed <xml> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);                }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                 }
	YY_BREAK



case 16:
YY_RULE_SETUP
#line 65 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                  }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 66 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                     }
	YY_BREAK
case YY_STATE_EOF(script_paired):
#line 67 "lexer.l"
{ ERROR_MESSAGE("Unclosed <script> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                   }
	YY_BREAK



case 19:
YY_RULE_SETUP
#line 73 "lexer.l"
{ DEBUG_MESSAGE("STYLE PAIRED ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                  }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 74 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                    }
	YY_BREAK
case YY_STATE_EOF(style_paired):
#line 75 "lexer.l"
{ ERROR_MESSAGE("Unclosed <style> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                  }
	YY_BREAK



case 22:
YY_RULE_SETUP
#line 81 "lexer.l"
{ DEBUG_MESSAGE("XML PAIRED ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                      }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 82 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                      }
	YY_BREAK
case YY_STATE_EOF(xml_paired):
#line 83 "lexer.l"
{ ERROR_MESSAGE("Unclosed <xml> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);                   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                    }
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 87 "lexer.l"
{  g_LexerColumn += yyleng; }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 88 "lexer.l"
{  g_LexerColumn = 0; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML);             }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "lexer.l"
{  return Token(yytext, DOCTYPE);                   }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "lexer.l"
{  return Token(yytext, DOCTYPE_HTML_5);            }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML);             }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "lexer.l"
{  return Token(yytext, DOCTYPE);                   }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "lexer.l"
{  return Token(yytext, DOCTYPE_HTML_5);            }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "lexer.l"
{  return Token(yytext, DOCTYPE_STRICT_1);          }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "lexer.l"
{  return Token(yytext, DOCTYPE_STRICT_2);          }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "lexer.l"
{  return Token(yytext, DOCTYPE_TRANS_1);           }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "lexer.l"
{  return Token(yytext, DOCTYPE_TRANS_2);           }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "lexer.l"
{  return Token(yytext, DOCTYPE_FRAME_1);           }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "lexer.l"
{  return Token(yytext, DOCTYPE_FRAME_2);           }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_STRICT_1);    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_STRICT_2);    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_TRANS_1);     }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_TRANS_2);     }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_FRAME_1);     }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_FRAME_2);     }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_1_1_1);       }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_1_1_2);       }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "lexer.l"
{  Token(yytext, SCRIPT_STARTED);   BEGIN(script);  }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "lexer.l"
{  Token(yytext, STYLE_STARTED);    BEGIN(style);   }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "lexer.l"
{  Token(yytext, XML_STARTED);      BEGIN(xml);     }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "lexer.l"
{  Token(yytext, COMMENT_STARTED);  BEGIN(comment); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "lexer.l"
{  Token(yytext, COMMENT_STARTED);  BEGIN(comment); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "lexer.l"
{  return Token(yytext, OPENING_TAG_BRACKET);       }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "lexer.l"
{  return Token(yytext, CLOSING_TAG_BRACKET);       }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "lexer.l"
{  return Token(yytext, ASSIGNMENT);                }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "lexer.l"
{  return Token(yytext, SLASH);                     }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 118 "lexer.l"
{  return Token(yytext, SINGLE_QUOTE_STRING);       }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 119 "lexer.l"
{  return Token(yytext, DOUBLE_QUOTE_STRING);       }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "lexer.l"
{  return Token(yytext, TEXT);                      }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "lexer.l"
ECHO;
	YY_BREAK
#line 1514 "lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 427 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 427 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 426);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 121 "lexer.l"

