#line 1 "lexer.cpp"

#line 3 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[397] =
    {   0,
       55,   55,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   57,   55,   25,   26,
       25,   55,   55,   55,   52,   49,   51,   50,    3,    2,
        3,    7,    6,    7,    5,   11,   10,   11,    9,   15,
       14,   15,   13,   18,   17,   18,   21,   20,   21,   24,
       23,   24,   55,   25,   25,   55,   55,    0,   54,   55,
       55,   55,   55,    0,   53,   55,    0,    0,    0,    0,
        4,    8,   12,    0,    0,    0,   55,   54,    0,    0,
       55,    0,   55,   53,    0,   55,    0,    0,    0,    0,
        0,    1,    0,    0,    0,   55,    0,   55,   48,    0,

        0,   46,    0,    0,    0,   55,    0,   55,   47,    0,
        0,    0,    0,    0,   55,    0,   55,    0,   45,    0,
        0,   22,   55,    0,    0,   44,    0,    0,   55,    0,
        0,    0,   19,    0,    0,    0,   16,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       29,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   28,   27,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       30,    0,    0,    0,   42,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   36,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   34,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,    0,    0,    0,    0,    0,    0,   31,
        0,    0,   32,   38,    0,    0,    0,   35,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   43,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   37,    0,    0,    0,   41,
        0,    0,    0,    0,   39,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   12,    1,
       13,   14,    1,    1,    1,    1,    1,   15,    1,   16,
       17,   18,    1,    1,    1,   19,   20,   21,   22,   23,
        1,   24,   25,    1,    1,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,    1,   35,   36,   37,    1,
       38,   39,    1,    1,    1,    1,   40,    1,   41,   42,

       43,   44,   45,   46,   47,    1,    1,   48,   49,   50,
       51,   52,    1,   53,   54,   55,    1,    1,   56,   57,
       58,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[414] =
    {   0,
        0,   17,    5,    6,   22,   26,   27,   28,   38,   39,
       12,   23,   44,   47,   48,   49,  828,    0,   51, 1027,
       57,  792,   63,   79, 1027,   49, 1027, 1027, 1027, 1027,
      804, 1027, 1027,  764, 1027, 1027, 1027,  747, 1027, 1027,
     1027,  735, 1027, 1027, 1027,  736, 1027, 1027,  735, 1027,
     1027,  715,    0,   66,   70,  695,   95,   37,    0,  104,
       74,  141,  121,   55,    0,  132,  698,   74,  623,  653,
     1027, 1027, 1027,  614,  570,  565,  601, 1027,    0,   94,
      158,   87,  195, 1027,    0,  175,   78,  608,  548,  519,
      522, 1027,  514,  498,  467,  468,  117,  248,  447,  432,

      428, 1027,  413,  407,  403,  383,  164,  298, 1027,  345,
      353,  344,  337,  364,  342,  126,  214,  299, 1027,  301,
      274, 1027,  290,  161,  163, 1027,  228,  257,  269,  177,
      180,  243, 1027,   95,  183,  182, 1027,  227,  186,  200,
      184,  198,  166,  188,  220,  181,  136,  204,  189,  177,
      168,  231,  229,  136,  125,  238,  250,  240,  120,  119,
      242,  251,  241,  121,  108,  256,  266,  257,   90,   62,
      272,  280,  279,   62,   52,  293,  316,  288,   55,   38,
      282,  291,  303, 1027, 1027,  124,  317,  319,  322,  327,
      325,  337,  340,  339,  323,  334,  342,  354,  353,  345,

      359,  362,  364,  368,  365,  369,  377,  388,  382,  383,
      389,  393,  406,  396,  400,  403,  413,  407,  405,  408,
      417,  419,  420,  431,  434,  442,  454,  443,  444,  455,
     1027,  456,  457,  458, 1027,  465,  468,  466,  471,  480,
      482,  483,  484,  496,  486,  494,  497,  505,  507,  508,
      518,  511,  520,  521,  533,  536,  537,  542,  539,  545,
      548,  550,  557,  552,  558,  559,  561,  573,  568,  574,
      576,  587,  588,  596,  598,  599,  608,  600,  605,  611,
      614,  619,  626,  625,  634,  627,  637,  635,  639,  636,
      642,  646,  655,  674,  663,  656,  664, 1027,  657,  671,

      676,  677,  681,  682,  683,  687,  692,  701,  693,  694,
      702,  703,  711, 1027,  713, 1027,  724,  729,  722,  723,
      730,  731,  737,  745,  741,  748,  749,  750,  754,  766,
      767,  760, 1027,  765,  769,  768,  771,  779,  784, 1027,
      794,  805, 1027, 1027,  786,  791,  808, 1027,  790,  795,
      803,  813,  815,  818,  821,  825,  826,  830,  831,  833,
      835,  843,  847,  834,  852,  853,  856,  857,  873,  874,
      860, 1027,  879,  881,  883,  888,  887,  892,  894,  896,
      898,  901,  905,  911,  913, 1027,  915,  908,  919, 1027,
      918,  923,  926,  933, 1027, 1027,  978,  981,  984,  987,

      990,  993,  996,  999,    0, 1002, 1005, 1008, 1011, 1014,
     1017, 1020, 1023
    } ;

static const flex_int16_t yy_def[414] =
    {   0,
      397,  397,  398,  398,  399,  399,  400,  400,  401,  401,
      402,  402,  403,  403,  404,  404,  396,  405,  405,  396,
      396,  405,  406,  407,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  405,  405,  396,  405,  406,  408,  405,  406,
      409,  406,  407,  410,  405,  411,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  405,  396,  412,  408,
      406,  408,  406,  396,  413,  407,  410,  396,  396,  396,
      396,  396,  396,  396,  396,  405,  408,  406,  396,  396,

      396,  396,  396,  396,  396,  405,  408,  406,  396,  396,
      396,  396,  396,  396,  405,  408,  406,  396,  396,  396,
      396,  396,  405,  408,  408,  396,  396,  396,  405,  408,
      408,  396,  396,  396,  408,  408,  396,  396,  396,  408,
      408,  396,  396,  408,  408,  396,  396,  408,  408,  396,
      396,  408,  408,  396,  396,  408,  408,  408,  396,  396,
      408,  408,  408,  396,  396,  408,  408,  408,  396,  396,
      408,  408,  408,  396,  396,  408,  408,  408,  396,  396,
      408,  408,  408,  396,  396,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      396,  408,  408,  408,  396,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  396,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  396,  408,  396,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  396,  408,  408,  408,  408,  408,  408,  396,
      408,  408,  396,  396,  408,  408,  408,  396,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  396,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  396,  408,  408,  408,  396,
      408,  408,  408,  408,  396,    0,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396
    } ;

static const flex_int16_t yy_nxt[1086] =
    {   0,
       53,   19,   20,   21,   22,   23,   24,   30,   30,   25,
      396,  396,   31,   31,   45,   26,   27,   28,   19,   20,
       21,   22,   23,   24,   33,   45,   25,   46,   33,   37,
       37,   34,   26,   27,   28,   34,   38,   38,   46,   35,
       41,   41,   78,   35,   39,   39,   48,   42,   42,   48,
       51,   51,   54,   67,   55,   43,   43,  185,   55,   49,
       55,   84,   49,   52,   52,   58,   58,   54,   59,   55,
       60,   55,   58,   55,  184,   79,  180,   82,   58,   58,
       58,   64,   64,   82,   84,   65,  179,  175,   64,   82,
       82,   82,   78,   85,   64,   64,   64,   58,   58,   78,

       59,   61,   68,   97,   58,   69,   58,   58,   62,   59,
       58,   58,   58,   80,   89,  174,   85,   66,  138,   58,
       58,   58,   78,   64,   64,   79,  170,   65,   90,   78,
       64,   78,   79,   61,  189,   87,   64,   64,   64,  169,
      139,   87,   61,   58,   58,  124,   59,   87,   87,   87,
       58,  107,  165,  164,  160,   79,   58,   58,   58,   66,
       58,   58,   79,   59,   79,  159,   78,   58,   78,   78,
      130,  155,  131,   58,   58,   58,  116,   64,   64,   61,
      154,   65,   78,  151,   64,   78,  135,   78,   78,   78,
       64,   64,   64,   78,   78,   83,   61,   58,   58,   79,

       59,   79,   79,  140,   58,   78,  150,  152,  148,   78,
       58,   58,   58,   66,  147,   79,   58,   58,   79,   59,
       79,   79,   79,  125,  146,   78,   79,   79,  149,   58,
       58,   58,  144,   61,   78,  136,   78,  141,   79,  145,
      143,  158,   79,   78,  153,   78,   78,   78,  163,   98,
       58,   58,   61,   59,  156,   78,   78,   58,   79,  142,
      137,   78,   78,   58,   58,   58,  157,   79,  166,   79,
      161,   78,  134,  162,  133,  176,   79,   78,   79,   79,
       79,  171,  132,  167,   78,   78,   61,   78,   79,   79,
      186,  168,  172,   78,   79,   79,   78,  183,   78,  108,

       58,   58,  187,   59,   79,  177,  181,   58,   78,  173,
       79,  129,  117,   58,   58,   58,  128,   79,   79,  182,
       79,   78,   78,  178,   78,  190,   79,   78,   78,   79,
       78,   79,   78,  192,  195,  188,   61,  193,  194,   78,
      196,   79,   78,  198,   78,   78,  197,   78,  199,  191,
       78,  204,  127,  126,   79,   79,  202,   79,   78,   78,
       79,   79,  208,   79,   78,   79,  203,   78,  200,   78,
       78,  123,   79,   78,   78,   79,  205,   79,   79,  201,
       79,  122,   78,   79,  121,  206,  207,   78,   78,  213,
      120,   79,   79,   78,   78,  119,  118,   79,   78,  209,

       79,   78,   79,   79,  210,   78,   79,   79,   78,  217,
       78,   78,   78,   78,  211,   79,  212,  214,   78,  115,
       79,   79,   78,  215,  231,   78,   79,   79,  220,  216,
      218,   79,  221,  222,   79,  223,   78,  219,   79,   78,
      226,   79,  225,   79,   79,   79,   79,  235,   78,   78,
      114,   79,  224,  228,  227,   79,  229,   79,   79,   78,
       78,   78,   78,   78,  113,  112,  230,  236,  232,   79,
       78,   78,   79,   78,  243,  111,   78,  233,  110,  244,
       79,   79,   79,  234,  109,   78,  238,   78,   78,   78,
      237,   78,   79,   79,   79,   79,   79,  241,  240,   78,

      106,   78,   78,   79,   79,  253,   79,  254,  239,   79,
       78,  242,   78,   78,  258,  105,   78,  246,   79,  245,
       79,   79,   79,   78,   79,   78,   78,  250,  255,  249,
      264,  251,   79,  247,   79,   79,  248,  252,   78,  257,
      263,   78,   78,   79,   78,   79,   79,   78,  256,   79,
       78,  268,  104,   78,  103,   78,   79,   78,   79,   79,
      260,  259,   78,   78,   78,  262,   78,  275,  261,  102,
      277,   79,  274,   78,   79,   79,  101,   79,   78,   78,
       79,   78,  266,   79,  270,  269,   79,  265,   79,  273,
       79,  267,   78,   78,  278,   79,   79,   79,  271,   79,

      100,   78,  272,   78,   78,   78,   79,  285,  283,  276,
       78,   79,   79,   78,   79,   99,   78,  287,  279,   78,
       96,   95,  280,   94,   78,   79,   79,  288,  284,  281,
       78,   78,   78,  282,   79,  293,   79,   79,   79,   78,
      298,   78,   78,   79,   78,  294,   79,   78,  286,   79,
      301,   78,   79,  290,  289,  295,  291,   79,  297,  292,
       78,   78,   78,   79,   79,   79,  296,   93,   78,   78,
       92,   91,   79,   79,   79,   79,   78,   79,  299,   78,
       79,   78,   78,  304,   79,  311,   78,   78,  314,  300,
      305,  307,   78,   79,   79,   79,  315,  316,   78,   78,

      302,   79,   79,  306,  308,   88,   78,   78,   78,   79,
      317,  303,   79,  309,   79,   79,   78,  310,   78,   79,
       79,   79,  323,   77,   76,   79,  312,   78,   78,   78,
       79,   79,   79,  324,   78,   78,   78,  325,  313,   79,
       79,   79,   78,  320,   75,   74,   78,  318,  319,   79,
       78,   79,   73,  333,   78,   78,  322,  321,  330,   78,
       79,   79,   79,  326,   72,   78,  331,   79,   79,   79,
      340,   78,   78,   78,   78,   79,  343,  327,  328,   79,
      341,   71,  332,   79,  344,  329,   79,   79,   79,   78,
      334,  348,   79,  337,  338,   78,   78,  335,   79,   78,

       78,  346,  336,   79,   79,   79,   79,   79,   78,   79,
       78,   70,   56,   78,  339,  342,  347,   79,   78,  352,
       78,  356,   79,   78,   79,  345,   78,  396,   79,   79,
       78,   78,   79,   79,  349,   78,   78,  396,   78,   78,
       78,   79,  353,   79,  350,  351,   79,  396,   78,  354,
      396,   79,   78,   79,  357,  355,   79,   78,   78,   79,
      359,   78,  372,   79,   79,   78,  360,  396,   79,   79,
      358,   79,   79,   79,  361,  368,  362,  365,   78,   78,
      363,   79,  374,  366,   78,   79,   78,  364,   78,  396,
       79,   79,   78,   78,   79,   79,  379,   78,   79,   78,

      367,   78,  371,   78,  396,  369,   78,  370,  396,  396,
      386,   79,   79,  390,  375,  373,   78,   79,   78,   79,
       78,   79,  377,   78,   78,   79,   79,  391,   78,  378,
       79,   78,   79,  376,   79,  382,   79,  383,  395,   79,
      396,  380,  381,   79,  396,  396,   79,  384,  396,   79,
      387,   79,  396,   79,  388,  385,   79,   79,  396,  392,
      396,   79,  389,  396,   79,  396,  396,  394,  396,  396,
      396,   79,  396,  396,  396,  396,  396,  393,   18,   18,
       18,   29,   29,   29,   32,   32,   32,   36,   36,   36,
       40,   40,   40,   44,   44,   44,   47,   47,   47,   50,

       50,   50,   57,   57,   57,   63,   63,   63,   58,   58,
       58,   81,  396,   81,   64,   64,   64,   86,  396,   86,
       82,  396,   82,   87,  396,   87,   17,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396
    } ;

static const flex_int16_t yy_chk[1086] =
    {   0,
      405,    1,    1,    1,    1,    1,    1,    3,    4,    1,
        0,    0,    3,    4,   11,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    5,   12,    2,   11,    6,    7,
        8,    5,    2,    2,    2,    6,    7,    8,   12,    5,
        9,   10,   58,    6,    7,    8,   13,    9,   10,   14,
       15,   16,   19,   26,   19,    9,   10,  180,   21,   13,
       21,   64,   14,   15,   16,   23,   23,   54,   23,   54,
       23,   55,   23,   55,  179,   58,  175,   61,   23,   23,
       23,   24,   24,   61,   87,   24,  174,  170,   24,   61,
       61,   61,   82,   64,   24,   24,   24,   57,   57,   80,

       57,   23,   26,   80,   57,   26,   60,   60,   23,   60,
       57,   57,   57,   60,   68,  169,   87,   24,  134,   60,
       60,   60,   97,   63,   63,   82,  165,   63,   68,  186,
       63,  116,   80,   57,  186,   66,   63,   63,   63,  164,
      134,   66,   60,   62,   62,  116,   62,   66,   66,   66,
       62,   97,  160,  159,  155,   97,   62,   62,   62,   63,
       81,   81,  186,   81,  116,  154,  124,   81,  125,  107,
      124,  151,  125,   81,   81,   81,  107,   86,   86,   62,
      150,   86,  130,  147,   86,  131,  130,  136,  135,  141,
       86,   86,   86,  144,  149,   62,   81,   83,   83,  124,

       83,  125,  107,  135,   83,  140,  146,  148,  144,  148,
       83,   83,   83,   86,  143,  130,  117,  117,  131,  117,
      136,  135,  141,  117,  142,  145,  144,  149,  145,  117,
      117,  117,  140,   83,  153,  131,  152,  136,  140,  141,
      139,  153,  148,  156,  149,  158,  163,  161,  158,   83,
       98,   98,  117,   98,  152,  157,  162,   98,  145,  138,
      132,  166,  168,   98,   98,   98,  152,  153,  161,  152,
      156,  167,  129,  157,  128,  171,  156,  171,  158,  163,
      161,  166,  127,  162,  173,  172,   98,  181,  157,  162,
      181,  163,  167,  178,  166,  168,  182,  178,  176,   98,

      108,  108,  182,  108,  167,  172,  176,  108,  183,  168,
      171,  123,  108,  108,  108,  108,  121,  173,  172,  177,
      181,  177,  187,  173,  188,  187,  178,  189,  195,  182,
      191,  176,  190,  189,  191,  183,  108,  190,  190,  196,
      192,  183,  192,  193,  194,  193,  192,  197,  194,  188,
      200,  197,  120,  118,  177,  187,  196,  188,  199,  198,
      189,  195,  199,  191,  201,  190,  196,  202,  195,  203,
      205,  115,  196,  204,  206,  192,  198,  194,  193,  195,
      197,  114,  207,  200,  113,  198,  198,  209,  210,  204,
      112,  199,  198,  208,  211,  111,  110,  201,  212,  200,

      202,  214,  203,  205,  201,  215,  204,  206,  216,  208,
      219,  213,  218,  220,  202,  207,  203,  205,  217,  106,
      209,  210,  221,  206,  222,  223,  208,  211,  211,  207,
      209,  212,  212,  213,  214,  214,  224,  210,  215,  225,
      217,  216,  216,  219,  213,  218,  220,  226,  228,  229,
      105,  217,  215,  219,  218,  221,  220,  222,  223,  227,
      230,  232,  233,  234,  104,  103,  221,  227,  223,  224,
      236,  238,  225,  237,  236,  101,  239,  224,  100,  237,
      226,  228,  229,  225,   99,  240,  229,  241,  242,  243,
      228,  245,  227,  230,  232,  233,  234,  233,  232,  246,

       96,  244,  247,  236,  238,  244,  237,  244,  230,  239,
      248,  234,  249,  250,  248,   95,  252,  239,  240,  238,
      241,  242,  243,  251,  245,  253,  254,  243,  245,  242,
      254,  243,  246,  240,  244,  247,  241,  243,  255,  247,
      253,  256,  257,  248,  259,  249,  250,  258,  246,  252,
      260,  258,   94,  261,   93,  262,  251,  264,  253,  254,
      250,  249,  263,  265,  266,  252,  267,  265,  251,   91,
      267,  255,  264,  269,  256,  257,   90,  259,  268,  270,
      258,  271,  256,  260,  260,  259,  261,  255,  262,  263,
      264,  257,  272,  273,  268,  263,  265,  266,  261,  267,

       89,  274,  262,  275,  276,  278,  269,  275,  273,  266,
      279,  268,  270,  277,  271,   88,  280,  277,  269,  281,
       77,   76,  270,   75,  282,  272,  273,  278,  274,  271,
      284,  283,  286,  272,  274,  283,  275,  276,  278,  285,
      288,  290,  287,  279,  289,  284,  277,  291,  276,  280,
      291,  292,  281,  280,  279,  285,  281,  282,  287,  282,
      293,  296,  299,  284,  283,  286,  286,   74,  295,  297,
       70,   69,  285,  288,  290,  287,  300,  289,  289,  294,
      291,  301,  302,  294,  292,  302,  303,  304,  305,  290,
      295,  297,  306,  293,  296,  299,  306,  307,  309,  310,

      292,  295,  297,  296,  299,   67,  308,  311,  312,  300,
      308,  293,  294,  300,  301,  302,  313,  301,  315,  303,
      304,  305,  315,   56,   52,  306,  303,  319,  320,  317,
      307,  309,  310,  317,  318,  321,  322,  318,  304,  308,
      311,  312,  323,  311,   49,   46,  325,  309,  310,  313,
      324,  315,   42,  326,  327,  328,  313,  312,  323,  329,
      319,  320,  317,  319,   38,  332,  324,  318,  321,  322,
      334,  330,  331,  336,  335,  323,  337,  320,  321,  325,
      335,   34,  325,  324,  338,  322,  326,  327,  328,  339,
      327,  345,  329,  330,  331,  349,  346,  328,  332,  341,

      350,  341,  329,  334,  330,  331,  336,  335,  351,  337,
      342,   31,   22,  347,  332,  336,  342,  338,  352,  347,
      353,  352,  339,  354,  345,  339,  355,   17,  349,  346,
      356,  357,  341,  350,  346,  358,  359,    0,  360,  364,
      361,  351,  349,  342,  346,  346,  347,    0,  362,  350,
        0,  352,  363,  353,  353,  351,  354,  365,  366,  355,
      355,  367,  368,  356,  357,  371,  356,    0,  358,  359,
      354,  360,  364,  361,  357,  364,  358,  361,  369,  370,
      359,  362,  370,  362,  373,  363,  374,  360,  375,    0,
      365,  366,  377,  376,  367,  368,  376,  378,  371,  379,

      363,  380,  367,  381,    0,  365,  382,  366,    0,    0,
      383,  369,  370,  388,  371,  369,  384,  373,  385,  374,
      387,  375,  374,  391,  389,  377,  376,  389,  392,  375,
      378,  393,  379,  373,  380,  379,  381,  380,  394,  382,
        0,  377,  378,  383,    0,    0,  388,  381,    0,  384,
      384,  385,    0,  387,  385,  382,  391,  389,    0,  391,
        0,  392,  387,    0,  393,    0,    0,  393,    0,    0,
        0,  394,    0,    0,    0,    0,    0,  392,  397,  397,
      397,  398,  398,  398,  399,  399,  399,  400,  400,  400,
      401,  401,  401,  402,  402,  402,  403,  403,  403,  404,

      404,  404,  406,  406,  406,  407,  407,  407,  408,  408,
      408,  409,    0,  409,  410,  410,  410,  411,    0,  411,
      412,    0,  412,  413,    0,  413,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[57] =
    {   0,
0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 
    1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define YY_NO_UNISTD_H 1
#line 6 "lexer.l"
    #include <stdio.h>
    #include <io.h>
    #include <string>
    #include "utils.h"
    #include "debug.h"
    #include "grammar.cpp.h"
    #pragma warning( disable:4996 )
    #pragma warning( disable:5033 )

    extern int yyerror(const char * err);
    int g_LexerColumn = 0;
#line 857 "lexer.cpp"

#line 859 "lexer.cpp"

#define INITIAL 0
#define comment 1
#define script 2
#define style 3
#define xml 4
#define script_paired 5
#define style_paired 6
#define xml_paired 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "lexer.l"

#line 1085 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 397 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1027 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "lexer.l"
{ DEBUG_MESSAGE("COMMENT ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);  BEGIN(INITIAL);                  }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 31 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                }
	YY_BREAK
case YY_STATE_EOF(comment):
#line 32 "lexer.l"
{ ERROR_MESSAGE("Unclosed comment", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                              }
	YY_BREAK



case 4:
YY_RULE_SETUP
#line 38 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT SINGLE ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);  BEGIN(INITIAL);                 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED START", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(script_paired);            }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 40 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                     }
	YY_BREAK
case YY_STATE_EOF(script):
#line 41 "lexer.l"
{ ERROR_MESSAGE("Unclosed <script> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                   }
	YY_BREAK



case 8:
YY_RULE_SETUP
#line 47 "lexer.l"
{ DEBUG_MESSAGE("STYLE SINGLE ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED START", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(style_paired);            }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 49 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                    }
	YY_BREAK
case YY_STATE_EOF(style):
#line 50 "lexer.l"
{ ERROR_MESSAGE("Unclosed <style> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                  }
	YY_BREAK



case 12:
YY_RULE_SETUP
#line 56 "lexer.l"
{ DEBUG_MESSAGE("XML SINGLE ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 57 "lexer.l"
{ DEBUG_MESSAGE("XML PAIRED START", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(xml_paired);                }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 58 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                   }
	YY_BREAK
case YY_STATE_EOF(xml):
#line 59 "lexer.l"
{ ERROR_MESSAGE("Unclosed <xml> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);                }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 60 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                 }
	YY_BREAK



case 16:
YY_RULE_SETUP
#line 65 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                  }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 66 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                     }
	YY_BREAK
case YY_STATE_EOF(script_paired):
#line 67 "lexer.l"
{ ERROR_MESSAGE("Unclosed <script> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                   }
	YY_BREAK



case 19:
YY_RULE_SETUP
#line 73 "lexer.l"
{ DEBUG_MESSAGE("STYLE PAIRED ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                  }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 74 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                    }
	YY_BREAK
case YY_STATE_EOF(style_paired):
#line 75 "lexer.l"
{ ERROR_MESSAGE("Unclosed <style> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);               }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                  }
	YY_BREAK



case 22:
YY_RULE_SETUP
#line 81 "lexer.l"
{ DEBUG_MESSAGE("XML PAIRED ENDED", DEBUG_CODE_LEXER, yylineno, g_LexerColumn); BEGIN(INITIAL);                      }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 82 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                      }
	YY_BREAK
case YY_STATE_EOF(xml_paired):
#line 83 "lexer.l"
{ ERROR_MESSAGE("Unclosed <xml> tag", ERROR_CODE_DOCUMENT, yylineno, g_LexerColumn); return (EOF);                   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno, g_LexerColumn);                                    }
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 87 "lexer.l"
{  g_LexerColumn += yyleng; }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 88 "lexer.l"
{  g_LexerColumn = 0; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML);             }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "lexer.l"
{  return Token(yytext, DOCTYPE);                   }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "lexer.l"
{  return Token(yytext, DOCTYPE_HTML_5);            }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "lexer.l"
{  return Token(yytext, DOCTYPE_STRICT_1);          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "lexer.l"
{  return Token(yytext, DOCTYPE_STRICT_2);          }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "lexer.l"
{  return Token(yytext, DOCTYPE_TRANS_1);           }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "lexer.l"
{  return Token(yytext, DOCTYPE_TRANS_2);           }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "lexer.l"
{  return Token(yytext, DOCTYPE_FRAME_1);           }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "lexer.l"
{  return Token(yytext, DOCTYPE_FRAME_2);           }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_STRICT_1);    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_STRICT_2);    }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_TRANS_1);     }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_TRANS_2);     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_FRAME_1);     }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_FRAME_2);     }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_1_1_1);       }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_1_1_2);       }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "lexer.l"
{  Token(yytext, SCRIPT_STARTED);   BEGIN(script);  }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "lexer.l"
{  Token(yytext, STYLE_STARTED);    BEGIN(style);   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "lexer.l"
{  Token(yytext, XML_STARTED);      BEGIN(xml);     }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "lexer.l"
{  Token(yytext, COMMENT_STARTED);  BEGIN(comment); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "lexer.l"
{  Token(yytext, COMMENT_STARTED);  BEGIN(comment); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "lexer.l"
{  return Token(yytext, OPENING_TAG_BRACKET);       }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "lexer.l"
{  return Token(yytext, CLOSING_TAG_BRACKET);       }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "lexer.l"
{  return Token(yytext, ASSIGNMENT);                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "lexer.l"
{  return Token(yytext, SLASH);                     }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 115 "lexer.l"
{  return Token(yytext, SINGLE_QUOTE_STRING);       }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 116 "lexer.l"
{  return Token(yytext, DOUBLE_QUOTE_STRING);       }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "lexer.l"
{  return Token(yytext, TEXT);                      }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "lexer.l"
ECHO;
	YY_BREAK
#line 1489 "lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 397 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 397 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 396);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 118 "lexer.l"

