#line 1 "lexer.cpp"

#line 3 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[396] =
    {   0,
       54,   54,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   56,   54,   25,   25,
       54,   54,   54,   51,   48,   50,   49,    3,    2,    3,
        7,    6,    7,    5,   11,   10,   11,    9,   15,   14,
       15,   13,   18,   17,   18,   21,   20,   21,   24,   23,
       24,   54,   25,   25,   54,   54,    0,   53,   54,   54,
       54,   54,    0,   52,   54,    0,    0,    0,    0,    4,
        8,   12,    0,    0,    0,   54,   53,    0,    0,   54,
        0,   54,   52,    0,   54,    0,    0,    0,    0,    0,
        1,    0,    0,    0,   54,    0,   54,   47,    0,    0,

       45,    0,    0,    0,   54,    0,   54,   46,    0,    0,
        0,    0,    0,   54,    0,   54,    0,   44,    0,    0,
       22,   54,    0,    0,   43,    0,    0,   54,    0,    0,
        0,   19,    0,    0,    0,   16,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   28,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   27,   26,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   29,
        0,    0,    0,   41,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   35,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,    0,   39,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   32,    0,    0,    0,    0,    0,    0,   30,    0,
        0,   31,   37,    0,    0,    0,   34,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       42,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   36,    0,    0,    0,   40,    0,
        0,    0,    0,   38,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    1,
        1,    1,    1,    1,    8,    9,   10,   11,   12,    1,
       13,   14,    1,    1,    1,    1,    1,   15,    1,   16,
       17,   18,    1,    1,    1,   19,   20,   21,   22,   23,
        1,   24,   25,    1,    1,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,    1,   35,   36,   37,    1,
       38,   39,    1,    1,    1,    1,   40,    1,   41,   42,

       43,   44,   45,   46,   47,    1,    1,   48,   49,   50,
       51,   52,    1,   53,   54,   55,    1,    1,   56,   57,
       58,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[413] =
    {   0,
        0,   17,    5,    6,   22,   26,   27,   28,   38,   39,
       12,   23,   44,   47,   48,   49,  834,    0,   51,   64,
      798,   65,   70, 1033,   38, 1033, 1033, 1033, 1033,  807,
     1033, 1033,  795, 1033, 1033, 1033,  787, 1033, 1033, 1033,
      782, 1033, 1033, 1033,  747, 1033, 1033,  731, 1033, 1033,
      718,    0,   87,   94,  688,   96,   55,    0,  111,  115,
      120,  135,   69,    0,  144,  672,   17,  625,  648, 1033,
     1033, 1033,  589,  568,  520,  537, 1033,    0,   95,  160,
       64,  163, 1033,    0,  178,   71,  548,  480,  470,  462,
     1033,  468,  452,  454,  468,  151,  187,  456,  436,  418,

     1033,  399,  380,  389,  399,  110,  204, 1033,  369,  358,
      347,  338,  359,  332,  186,  224,  301, 1033,  299,  307,
     1033,  320,  162,  177, 1033,  286,  287,  300,  205,  192,
      265, 1033,   38,  101,  194, 1033,  248,  174,  218,  206,
      186,  160,  150,  226,  181,  136,  232,  217,  161,  159,
      231,  240,  128,  125,  221,  252,  243,  112,  110,  241,
      253,  255,  124,  122,  258,  260,  263,   94,   73,  268,
      269,  272,   68,   60,  271,  284,  283,   59,   39,  292,
      297,  294, 1033, 1033,  307,  306,  290,  308,  313,  320,
      328,  331,  333,  322,  342,  334,  351,  343,  348,  349,

      352,  354,  358,  357,  360,  363,  370,  365,  372,  379,
      383,  392,  394,  400,  402,  407,  406,  411,  418,  419,
      420,  422,  423,  424,  426,  434,  437,  438,  441, 1033,
      443,  449,  445, 1033,  458,  466,  450,  469,  473,  481,
      485,  486,  490,  492,  487,  500,  505,  507,  508,  512,
      511,  516,  513,  515,  532,  535,  539,  542,  547,  552,
      553,  561,  554,  558,  559,  563,  566,  570,  574,  576,
      577,  578,  579,  598,  589,  601,  608,  595,  590,  613,
      614,  621,  620,  626,  629,  632,  619,  636,  638,  640,
      644,  645,  651,  657,  656,  658, 1033,  661,  664,  666,

      672,  667,  676,  681,  683,  682,  688,  685,  695,  704,
      706,  708, 1033,  713, 1033,  719,  726,  720,  712,  724,
      725,  731,  733,  732,  710,  736,  738,  730,  754,  760,
      742, 1033,  750,  778,  762,  770,  777,  779, 1033,  786,
      790, 1033, 1033,  781,  789,  792, 1033,  785,  797,  800,
      802,  806,  801,  808,  816,  817,  820,  821,  824,  826,
      829,  836,  843,  844,  845,  855,  856,  858,  867,  866,
     1033,  868,  871,  872,  883,  875,  881,  885,  887,  897,
      898,  902,  903,  906, 1033,  910,  911,  922, 1033,  912,
      927,  928,  929, 1033, 1033,  982,  985,  988,  991,  994,

      997, 1000, 1003, 1006, 1008, 1011, 1014, 1017, 1020, 1023,
     1026, 1029
    } ;

static const flex_int16_t yy_def[413] =
    {   0,
      396,  396,  397,  397,  398,  398,  399,  399,  400,  400,
      401,  401,  402,  402,  403,  403,  395,  404,  404,  395,
      404,  405,  406,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  404,  404,  395,  404,  405,  407,  404,  405,  408,
      405,  406,  409,  404,  410,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  404,  395,  411,  407,  405,
      407,  405,  395,  412,  406,  409,  395,  395,  395,  395,
      395,  395,  395,  395,  404,  407,  405,  395,  395,  395,

      395,  395,  395,  395,  404,  407,  405,  395,  395,  395,
      395,  395,  395,  404,  407,  405,  395,  395,  395,  395,
      395,  404,  407,  407,  395,  395,  395,  404,  407,  407,
      395,  395,  395,  407,  407,  395,  395,  395,  407,  407,
      395,  395,  407,  407,  395,  395,  407,  407,  395,  395,
      407,  407,  395,  395,  407,  407,  407,  395,  395,  407,
      407,  407,  395,  395,  407,  407,  407,  395,  395,  407,
      407,  407,  395,  395,  407,  407,  407,  395,  395,  407,
      407,  407,  395,  395,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,

      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  395,
      407,  407,  407,  395,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  395,  407,  407,  407,

      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  395,  407,  395,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  395,  407,  407,  407,  407,  407,  407,  395,  407,
      407,  395,  395,  407,  407,  407,  395,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      395,  407,  407,  407,  407,  407,  407,  407,  407,  407,
      407,  407,  407,  407,  395,  407,  407,  407,  395,  407,
      407,  407,  407,  395,    0,  395,  395,  395,  395,  395,

      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395
    } ;

static const flex_int16_t yy_nxt[1092] =
    {   0,
      395,   19,   19,   20,   21,   22,   23,   29,   29,   24,
      395,  395,   30,   30,   44,   25,   26,   27,   19,   19,
       20,   21,   22,   23,   32,   44,   24,   45,   32,   36,
       36,   33,   25,   26,   27,   33,   37,   37,   45,   34,
       40,   40,   66,   34,   38,   38,   47,   41,   41,   47,
       50,   50,   53,   53,   54,   42,   42,   88,  184,   48,
       77,  137,   48,   51,   51,   54,   54,   54,   57,   77,
       58,   89,   59,   63,   57,   83,   64,   83,  183,   63,
       57,   57,   57,  138,  179,   63,   63,   63,   53,   53,
       54,   67,  178,   78,   68,   54,   54,   54,  174,   57,

       77,   58,   78,   60,   96,   57,   77,   84,   65,   84,
       61,   57,   57,   57,   57,   77,   58,   52,   81,  173,
       79,  139,  115,   57,   81,   58,   57,   57,   57,   57,
       81,   81,   81,   78,   60,   57,   57,   57,   63,   78,
      169,   64,  168,  164,   63,  163,   52,   86,   78,   60,
       63,   63,   63,   86,  159,   77,   77,  158,   60,   86,
       86,   86,  154,   57,  153,   58,   57,   77,   58,   57,
      147,  129,   57,   65,   82,   57,   57,   57,   57,   57,
       57,   63,   77,  150,   64,  106,  130,   63,   78,   78,
       57,   77,   58,   63,   63,   63,   57,   77,   60,   77,

       78,   60,   57,   57,   57,  123,  149,   57,  146,   58,
       77,   77,  145,   57,  134,   78,   65,   97,  116,   57,
       57,   57,   77,   77,   78,   60,   77,   57,  142,   58,
       78,   77,   78,  124,  148,  151,   77,   77,  107,   57,
       57,   57,   60,   78,   78,   77,   77,  135,   77,  140,
      143,  162,  157,  160,  155,   78,   78,   77,   77,   78,
       77,  144,   60,   77,   78,   77,  156,  165,   77,   78,
       78,  175,  152,   77,   77,  161,   77,   77,   78,   78,
      141,   78,  136,  170,  180,  166,  171,  181,   77,   77,
       78,   78,  182,   78,  176,   77,   78,   77,   78,   77,

      185,   78,   77,  133,  132,  167,   78,   78,  186,   78,
       78,   77,   77,   77,  189,  172,  177,  188,   77,  191,
      190,   78,   78,  192,  193,   77,  187,   77,   78,  194,
       78,  195,   78,   77,  197,   78,   77,  196,   77,   77,
      131,  128,  198,  203,   78,   78,   78,   77,   77,  127,
      126,   78,  207,   77,   77,  125,   77,   77,   78,   77,
       78,  122,   77,   77,  201,   77,   78,  199,   77,   78,
       77,   78,   78,  204,  202,   77,  121,   77,  200,  212,
       78,   78,  205,  206,   77,  120,   78,   78,   77,   78,
       78,  216,   78,  119,  209,   78,   78,   77,   78,   77,

      118,   78,  208,   78,  210,   77,  211,   77,   78,  213,
       78,   77,   77,  217,  214,  215,   77,   78,  219,  221,
      117,   78,  220,   77,   77,  230,  218,   77,   77,   77,
       78,  234,   78,  222,  225,  114,  113,  112,   78,   77,
       78,  224,   77,   77,   78,   78,   77,  235,   77,   78,
       77,  111,  223,  226,   77,   77,   78,   78,   78,  227,
       78,   78,   78,   77,   78,  110,  228,  242,  229,  232,
      231,   77,   78,  233,   77,   78,   78,  243,   77,   78,
      237,   78,  109,   78,  236,  239,   77,   78,   78,  240,
       77,   77,   77,  108,  238,   77,   78,   77,  241,  252,

      105,  253,  104,  244,   78,   77,  103,   78,  102,  101,
       77,   78,   77,   77,  257,  245,   77,   77,   77,   78,
       77,   77,  263,   78,   78,   78,  246,  100,   78,  249,
       78,  248,   99,  250,  254,  247,  262,   77,   78,  251,
       77,  255,  256,   78,   77,   78,   78,   77,  267,   78,
       78,   78,   77,   78,   78,   98,   95,   77,   77,   77,
      259,  258,  260,   77,   77,  261,   77,  274,   77,  264,
       78,   77,  276,   78,  273,   77,   94,   78,  265,   77,
       78,   77,   77,   77,   77,   78,  269,  277,  268,  266,
       78,   78,   78,  272,   77,   77,   78,   78,  282,   78,

       77,   78,  270,   77,   78,  271,   77,  284,   78,  275,
      286,  283,   78,   77,   78,   78,   78,   78,   77,   77,
      278,   93,  279,  281,  297,   77,   77,   78,   78,  280,
      292,   77,  289,   78,   77,  287,   78,   77,  285,   78,
      293,   77,   92,   77,  288,   77,   78,  294,  300,   77,
       77,   78,   78,  296,  291,  290,   77,   78,   78,   78,
      303,   77,   77,   77,   78,   91,   77,   78,  295,   77,
       78,   77,   77,   90,   78,  298,   78,   77,   78,   87,
      310,   77,   78,   78,  304,  306,  313,  315,   77,   78,
       77,  299,  314,   77,   78,   78,   78,  316,  301,   78,

       77,  302,   78,  305,   78,   78,  308,  309,  307,   77,
       78,   77,  311,   77,   78,  332,   76,   77,   77,   78,
       78,   78,  322,   78,   77,   77,   78,   75,  323,   77,
       77,   77,  312,   78,  324,   77,   77,   77,   77,  317,
       74,   77,   78,   77,   78,  319,   78,   77,   78,  318,
       78,   78,  329,  321,  330,  339,   73,   78,   78,   77,
      320,  325,   78,   78,   78,   77,  326,   77,   78,   78,
       78,   78,  327,  331,   78,  342,   78,  333,  335,  328,
       78,  336,  343,   77,   77,  334,  347,  337,   78,  340,
       77,   77,   78,  345,   77,   77,  338,   77,   78,   72,

       78,  346,   77,  351,   71,   77,   77,   77,   78,  341,
      355,   77,   70,   77,   69,   78,   78,   78,   55,   78,
      344,   77,   77,   78,   78,   77,   77,   78,   78,   77,
       78,   77,  348,  395,   77,   78,  395,  352,   78,   78,
       78,   77,  349,  350,   78,  356,   78,  358,   77,   77,
       77,  353,  354,  357,   78,   78,  395,  359,   78,   78,
       77,  371,   78,   77,   78,  360,  361,   78,  364,  365,
      362,   77,   77,   77,   78,  373,   77,   77,  363,  395,
       77,   78,   78,   78,  367,  395,   77,  395,   77,  366,
       77,  378,   77,   78,   78,  395,   78,  368,  395,  369,

      372,  370,   77,   77,   78,   78,   78,  385,   77,   78,
       78,   77,  376,   78,  395,   77,  389,   77,  377,   78,
      374,   78,  375,   78,  395,   78,  381,   77,  382,  379,
      390,  380,   77,   77,  394,   78,   78,  395,  395,  395,
       78,   78,  386,  395,   78,  395,  383,  387,   78,   78,
       78,  395,  384,  391,  395,  395,  395,  388,  395,  395,
       78,  395,  395,  395,  395,   78,   78,   78,  395,  393,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  392,   18,   18,   18,   28,   28,   28,   31,   31,
       31,   35,   35,   35,   39,   39,   39,   43,   43,   43,

       46,   46,   46,   49,   49,   49,   52,   52,   56,   56,
       56,   62,   62,   62,   57,   57,   57,   80,   80,   80,
       63,   63,   63,   85,   85,   85,   81,  395,   81,   86,
      395,   86,   17,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395

    } ;

static const flex_int16_t yy_chk[1092] =
    {   0,
        0,    1,    1,    1,    1,    1,    1,    3,    4,    1,
        0,    0,    3,    4,   11,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    5,   12,    2,   11,    6,    7,
        8,    5,    2,    2,    2,    6,    7,    8,   12,    5,
        9,   10,   25,    6,    7,    8,   13,    9,   10,   14,
       15,   16,   19,   19,   19,    9,   10,   67,  179,   13,
       57,  133,   14,   15,   16,   20,   20,   20,   22,   81,
       22,   67,   22,   23,   22,   63,   23,   86,  178,   23,
       22,   22,   22,  133,  174,   23,   23,   23,   53,   53,
       53,   25,  173,   57,   25,   54,   54,   54,  169,   56,

       79,   56,   81,   22,   79,   56,  134,   63,   23,   86,
       22,   56,   56,   56,   59,  106,   59,   60,   60,  168,
       59,  134,  106,   61,   60,   61,   59,   59,   59,   61,
       60,   60,   60,   79,   56,   61,   61,   61,   62,  134,
      164,   62,  163,  159,   62,  158,   65,   65,  106,   59,
       62,   62,   62,   65,  154,  143,   96,  153,   61,   65,
       65,   65,  150,   80,  149,   80,   82,  123,   82,   80,
      143,  123,   82,   62,   61,   80,   80,   80,   82,   82,
       82,   85,  124,  146,   85,   96,  124,   85,  143,   96,
       97,  115,   97,   85,   85,   85,   97,  130,   80,  135,

      123,   82,   97,   97,   97,  115,  145,  107,  142,  107,
      129,  140,  141,  107,  129,  124,   85,   82,  107,  107,
      107,  107,  148,  139,  115,   97,  155,  116,  138,  116,
      130,  144,  135,  116,  144,  147,  151,  147,   97,  116,
      116,  116,  107,  129,  140,  152,  160,  130,  157,  135,
      139,  157,  152,  155,  151,  148,  139,  156,  161,  155,
      162,  140,  116,  165,  144,  166,  151,  160,  167,  151,
      147,  170,  148,  170,  171,  156,  175,  172,  152,  160,
      137,  157,  131,  165,  175,  161,  166,  176,  177,  176,
      156,  161,  177,  162,  171,  187,  165,  180,  166,  182,

      180,  167,  181,  128,  127,  162,  170,  171,  181,  175,
      172,  186,  185,  188,  186,  167,  172,  185,  189,  188,
      187,  177,  176,  189,  189,  190,  182,  194,  187,  190,
      180,  191,  182,  191,  192,  181,  192,  191,  193,  196,
      126,  122,  193,  196,  186,  185,  188,  195,  198,  120,
      119,  189,  198,  199,  200,  117,  197,  201,  190,  202,
      194,  114,  204,  203,  195,  205,  191,  194,  206,  192,
      208,  193,  196,  197,  195,  207,  113,  209,  194,  203,
      195,  198,  197,  197,  210,  112,  199,  200,  211,  197,
      201,  207,  202,  111,  200,  204,  203,  212,  205,  213,

      110,  206,  199,  208,  201,  214,  202,  215,  207,  204,
      209,  217,  216,  208,  205,  206,  218,  210,  210,  212,
      109,  211,  211,  219,  220,  221,  209,  222,  223,  224,
      212,  225,  213,  213,  216,  105,  104,  103,  214,  226,
      215,  215,  227,  228,  217,  216,  229,  226,  231,  218,
      233,  102,  214,  217,  232,  237,  219,  220,  221,  218,
      222,  223,  224,  235,  225,  100,  219,  235,  220,  223,
      222,  236,  226,  224,  238,  227,  228,  236,  239,  229,
      228,  231,   99,  233,  227,  231,  240,  232,  237,  232,
      241,  242,  245,   98,  229,  243,  235,  244,  233,  243,

       95,  243,   94,  237,  236,  246,   93,  238,   92,   90,
      247,  239,  248,  249,  247,  238,  251,  250,  253,  240,
      254,  252,  253,  241,  242,  245,  239,   89,  243,  242,
      244,  241,   88,  242,  244,  240,  252,  255,  246,  242,
      256,  245,  246,  247,  257,  248,  249,  258,  257,  251,
      250,  253,  259,  254,  252,   87,   76,  260,  261,  263,
      249,  248,  250,  264,  265,  251,  262,  264,  266,  254,
      255,  267,  266,  256,  263,  268,   75,  257,  255,  269,
      258,  270,  271,  272,  273,  259,  259,  267,  258,  256,
      260,  261,  263,  262,  275,  279,  264,  265,  272,  262,

      278,  266,  260,  274,  267,  261,  276,  274,  268,  265,
      276,  273,  269,  277,  270,  271,  272,  273,  280,  281,
      268,   74,  269,  271,  287,  283,  282,  275,  279,  270,
      282,  284,  279,  278,  285,  277,  274,  286,  275,  276,
      283,  288,   73,  289,  278,  290,  277,  284,  290,  291,
      292,  280,  281,  286,  281,  280,  293,  287,  283,  282,
      293,  295,  294,  296,  284,   69,  298,  285,  285,  299,
      286,  300,  302,   68,  288,  288,  289,  301,  290,   66,
      301,  303,  291,  292,  294,  296,  304,  306,  305,  293,
      308,  289,  305,  307,  295,  294,  296,  307,  291,  298,

      309,  292,  299,  295,  300,  302,  299,  300,  298,  310,
      301,  311,  302,  312,  303,  325,   55,  319,  314,  304,
      306,  305,  314,  308,  316,  318,  307,   51,  316,  320,
      321,  317,  303,  309,  317,  328,  322,  324,  323,  308,
       48,  326,  310,  327,  311,  310,  312,  331,  325,  309,
      319,  314,  322,  312,  323,  333,   45,  316,  318,  329,
      311,  318,  320,  321,  317,  330,  319,  335,  328,  322,
      324,  323,  320,  324,  326,  336,  327,  326,  328,  321,
      331,  329,  337,  334,  338,  327,  344,  330,  333,  334,
      348,  340,  329,  340,  345,  341,  331,  346,  330,   41,

      335,  341,  349,  346,   37,  350,  353,  351,  336,  335,
      351,  352,   33,  354,   30,  337,  334,  338,   21,  344,
      338,  355,  356,  348,  340,  357,  358,  345,  341,  359,
      346,  360,  345,   17,  361,  349,    0,  348,  350,  353,
      351,  362,  345,  345,  352,  352,  354,  354,  363,  364,
      365,  349,  350,  353,  355,  356,    0,  355,  357,  358,
      366,  367,  359,  368,  360,  356,  357,  361,  360,  361,
      358,  370,  369,  372,  362,  369,  373,  374,  359,    0,
      376,  363,  364,  365,  363,    0,  377,    0,  375,  362,
      378,  375,  379,  366,  367,    0,  368,  364,    0,  365,

      368,  366,  380,  381,  370,  369,  372,  382,  383,  373,
      374,  384,  373,  376,    0,  386,  387,  390,  374,  377,
      370,  375,  372,  378,    0,  379,  378,  388,  379,  376,
      388,  377,  391,  392,  393,  380,  381,    0,    0,    0,
      382,  383,  383,    0,  384,    0,  380,  384,  386,  387,
      390,    0,  381,  390,    0,    0,    0,  386,    0,    0,
      388,    0,    0,    0,    0,  391,  392,  393,    0,  392,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  391,  396,  396,  396,  397,  397,  397,  398,  398,
      398,  399,  399,  399,  400,  400,  400,  401,  401,  401,

      402,  402,  402,  403,  403,  403,  404,  404,  405,  405,
      405,  406,  406,  406,  407,  407,  407,  408,  408,  408,
      409,  409,  409,  410,  410,  410,  411,    0,  411,  412,
        0,  412,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  395,  395,
      395

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[56] =
    {   0,
0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 
    1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define YY_NO_UNISTD_H 1
#line 6 "lexer.l"
    #include <stdio.h>
    #include <io.h>
    #include <string>
    #include "utils.h"
    #include "debug.h"
    #include "grammar.cpp.h"
    #pragma warning( disable:4996 )
    #pragma warning( disable:5033 )

    extern int yyerror(const char * err);
#line 860 "lexer.cpp"

#line 862 "lexer.cpp"

#define INITIAL 0
#define comment 1
#define script 2
#define style 3
#define xml 4
#define script_paired 5
#define style_paired 6
#define xml_paired 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 26 "lexer.l"

#line 1088 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 396 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1033 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "lexer.l"
{ DEBUG_MESSAGE("COMMENT ENDED", DEBUG_CODE_LEXER, yylineno);  BEGIN(INITIAL);                  }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 30 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                }
	YY_BREAK
case YY_STATE_EOF(comment):
#line 31 "lexer.l"
{ ERROR_MESSAGE("Unclosed comment", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 32 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                              }
	YY_BREAK



case 4:
YY_RULE_SETUP
#line 37 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT SINGLE ENDED", DEBUG_CODE_LEXER, yylineno);  BEGIN(INITIAL);                 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED START", DEBUG_CODE_LEXER, yylineno); BEGIN(script_paired);            }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 39 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                     }
	YY_BREAK
case YY_STATE_EOF(script):
#line 40 "lexer.l"
{ ERROR_MESSAGE("Unclosed <script> tag", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);  }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                                   }
	YY_BREAK



case 8:
YY_RULE_SETUP
#line 46 "lexer.l"
{ DEBUG_MESSAGE("STYLE SINGLE ENDED", DEBUG_CODE_LEXER, yylineno); BEGIN(INITIAL);                  }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED START", DEBUG_CODE_LEXER, yylineno); BEGIN(style_paired);            }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 48 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                    }
	YY_BREAK
case YY_STATE_EOF(style):
#line 49 "lexer.l"
{ ERROR_MESSAGE("Unclosed <style> tag", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                                  }
	YY_BREAK



case 12:
YY_RULE_SETUP
#line 55 "lexer.l"
{ DEBUG_MESSAGE("XML SINGLE ENDED", DEBUG_CODE_LEXER, yylineno); BEGIN(INITIAL);                   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "lexer.l"
{ DEBUG_MESSAGE("XML PAIRED START", DEBUG_CODE_LEXER, yylineno); BEGIN(xml_paired);                }
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 57 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                   }
	YY_BREAK
case YY_STATE_EOF(xml):
#line 58 "lexer.l"
{ ERROR_MESSAGE("Unclosed <xml> tag", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);   }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 59 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                                 }
	YY_BREAK



case 16:
YY_RULE_SETUP
#line 64 "lexer.l"
{ DEBUG_MESSAGE("SCRIPT PAIRED ENDED", DEBUG_CODE_LEXER, yylineno); BEGIN(INITIAL);                  }
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 65 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                     }
	YY_BREAK
case YY_STATE_EOF(script_paired):
#line 66 "lexer.l"
{ ERROR_MESSAGE("Unclosed <script> tag", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);  }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 67 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                                   }
	YY_BREAK



case 19:
YY_RULE_SETUP
#line 72 "lexer.l"
{ DEBUG_MESSAGE("STYLE PAIRED ENDED", DEBUG_CODE_LEXER, yylineno); BEGIN(INITIAL);                  }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 73 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                    }
	YY_BREAK
case YY_STATE_EOF(style_paired):
#line 74 "lexer.l"
{ ERROR_MESSAGE("Unclosed <style> tag", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);  }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 75 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                                  }
	YY_BREAK



case 22:
YY_RULE_SETUP
#line 80 "lexer.l"
{ DEBUG_MESSAGE("XML PAIRED ENDED", DEBUG_CODE_LEXER, yylineno); BEGIN(INITIAL);                      }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 81 "lexer.l"
{ DEBUG_MESSAGE("INGNORE NEW LINE", DEBUG_CODE_LEXER, yylineno);                                      }
	YY_BREAK
case YY_STATE_EOF(xml_paired):
#line 82 "lexer.l"
{ ERROR_MESSAGE("Unclosed <xml> tag", ERROR_CODE_DOCUMENT, yylineno);  system("pause"); exit(0);      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 83 "lexer.l"
{ DEBUG_MESSAGE("INGORING SOMETHING", DEBUG_CODE_LEXER, yylineno);                                    }
	YY_BREAK

case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 86 "lexer.l"
{ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 87 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML);             }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 88 "lexer.l"
{  return Token(yytext, DOCTYPE);                   }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 89 "lexer.l"
{  return Token(yytext, DOCTYPE_HTML_5);            }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "lexer.l"
{  return Token(yytext, DOCTYPE_STRICT_1);          }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "lexer.l"
{  return Token(yytext, DOCTYPE_STRICT_2);          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "lexer.l"
{  return Token(yytext, DOCTYPE_TRANS_1);           }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 93 "lexer.l"
{  return Token(yytext, DOCTYPE_TRANS_2);           }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 94 "lexer.l"
{  return Token(yytext, DOCTYPE_FRAME_1);           }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 "lexer.l"
{  return Token(yytext, DOCTYPE_FRAME_2);           }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_STRICT_1);    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 97 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_STRICT_2);    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_TRANS_1);     }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 99 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_TRANS_2);     }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 100 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_FRAME_1);     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_FRAME_2);     }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_1_1_1);       }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 103 "lexer.l"
{  return Token(yytext, DOCTYPE_XHTML_1_1_2);       }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 "lexer.l"
{  Token(yytext, SCRIPT_STARTED);   BEGIN(script);  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "lexer.l"
{  Token(yytext, STYLE_STARTED);    BEGIN(style);   }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 106 "lexer.l"
{  Token(yytext, XML_STARTED);      BEGIN(xml);     }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 107 "lexer.l"
{  Token(yytext, COMMENT_STARTED);  BEGIN(comment); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 108 "lexer.l"
{  Token(yytext, COMMENT_STARTED);  BEGIN(comment); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 109 "lexer.l"
{  return Token(yytext, OPENING_TAG_BRACKET);       }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 110 "lexer.l"
{  return Token(yytext, CLOSING_TAG_BRACKET);       }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "lexer.l"
{  return Token(yytext, ASSIGNMENT);                }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "lexer.l"
{  return Token(yytext, SLASH);                     }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 113 "lexer.l"
{  return Token(yytext, SINGLE_QUOTE_STRING);       }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 114 "lexer.l"
{  return Token(yytext, DOUBLE_QUOTE_STRING);       }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 115 "lexer.l"
{  return Token(yytext, TEXT);                      }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "lexer.l"
ECHO;
	YY_BREAK
#line 1488 "lexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 396 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 396 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 395);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 116 "lexer.l"

