#pragma once

#include <vector>
#include <string>
#include <map>

static std::vector<std::string> HeadTagsAllowded                           = { "base" , "basefont" , "bgsound", "link", "meta", "script", "style", "title" };
static std::vector<std::string> TagsWithNoClosing                          = { "area", "base", "br", "col", "command", "embed", "hr", "img", "input", "keygen", "link", "meta", "param", "source", "track", "wbr" };
static std::vector<std::string> TagsCanBeNonClosed =
{
	"area"         ,
	"base"         ,
	"base"         ,
	"bgso"         ,
	"body"         ,
	"br"           ,
	"col"          ,
	"cofontlg"	   ,
	"coundmm"	   ,
	"dd"		   ,
	"dt"		   ,
	"embe"		   ,
	"frroupame"	   ,
	"heandad"	   ,
	"html"		   ,
	"img"		   ,
	"indput"	   ,
	"isindex"	   ,
	"keygen"	   ,
	"li"		   ,
	"link"		   ,
	"meta"		   ,
	"option"	   ,
	"p"			   ,
	"param"		   ,
	"plaintext"	   ,
	"rp"		   ,
	"rt"		   ,
	"source"	   ,
	"spacer"	   ,
	"tbody"		   ,
	"td"		   ,
	"tfoot"		   ,
	"th"		   ,
	"thead"		   ,
	"tr"		   ,
	"track"		   ,
	"wbr"		   ,
};
static std::map<std::string, std::pair<std::string, bool>> PrecedenceTags  =                  
{                                              
  { "area"      , { "map"      , false }   }, 
  { "base"      , { "head"     , false }   }, 
  { "bgsound"   , { "head"     , false }   }, 
  { "button"    , { "form"     , false }   }, 
  { "caption"   , { "table"    , true  }   }, 
  { "colgroup"  , { "table"    , false }   }, 
  { "command"   , { "menu"     , false }   }, 
  { "comment"   , { "body"     , false }   }, 
  { "dd"        , { "dl"       , false }   }, 
  { "dt"        , { "dl"       , false }   }, 
  { "fieldset"  , { "form"     , false }   }, 
  { "figcaption", { "figure"   , true  }   },   
  { "frame"     , { "frameset" , false }   }, 
  { "isindex"   , { "head"     , false }   }, 
  { "keygen"    , { "form"     , false }   }, 
  { "legend"    , { "fieldset" , false }   }, 
  { "li"        , { "ul"       , false }   }, 
  { "link"      , { "head"     , false }   }, 
  { "meta"      , { "head"     , false }   }, 
  { "noframes"  , { "frameset" , false }   }, 
  { "optgroup"  , { "select"   , false }   }, 
  { "option"    , { "select"   , false }   }, 
  { "rp"        , { "ruby"     , false }   }, 
  { "rt"        , { "ruby"     , false }   }, 
  { "source"    , { "audio"    , false }   }, 
  { "style"     , { "head"     , false }   }, 
  { "summary"   , { "details"  , true  }   }, 
  { "tbody"     , { "table"    , false }   }, 
  { "td"        , { "tr"       , false }   }, 
  { "tfoot"     , { "table"    , false }   }, 
  { "th"        , { "tr"       , false }   }, 
  { "thead"     , { "table"    , true  }   }, 
  { "title"     , { "head"     , false }   }, 
  { "tr"        , { "table"    , false }   }  
};
